services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.database
    container_name: home_library_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: home_library_app
    restart: always
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      - PORT=${PORT}
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./generated:/app/generated
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.build.json:/app/tsconfig.build.json
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    networks:
      - app_network
    command:
      [
    #     'npm',
    #     'run',
    #     'prisma:migrate',
    #     '&&',
    #     'npm',
    #     'run',
    #     'prisma:generate',
    #     '&&',
        'npm',
        'run',
        'start:dev',
      ]

volumes:
  db_data:
    driver: local

networks:
  app_network:
    driver: bridge
