
FROM node:lts-slim AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY tsconfig*.json ./
COPY src/ ./src
COPY prisma ./prisma
COPY generated ./generated

RUN npm run build

FROM node:lts-slim AS runner
WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY package*.json ./
COPY prisma ./prisma
COPY generated ./generated
RUN npm ci --production

ARG PORT=3000
ENV PORT=${PORT}
EXPOSE ${PORT}

CMD ["sh", "-c", "npm run prisma:deploy"]