
FROM node:lts-slim AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY tsconfig*.json ./
COPY src/ ./src
COPY prisma ./prisma

RUN npx prisma generate
RUN npm run build

FROM node:lts-slim AS runner
WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/generated ./generated
COPY --from=builder /app/prisma ./prisma
COPY package*.json ./
RUN npm ci --production

ARG PORT=3000
ENV PORT=${PORT}
EXPOSE ${PORT}

CMD ["sh", "-c", "npm run prisma:deploy && npm run start:prod"]